#!/bin/sh

documents=$(mktemp -d /tmp/libreoffice.XXXXXXXX)

docker run --rm -d \
    --cap-drop=all \
    -c 2 \
    -m 1024M \
    -v /etc/localtime:/etc/localtime:ro \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e DISPLAY=unix$DISPLAY \
    -v ${documents}:/libreoffice/Documents \
    -e GDK_SCALE \
    -e GDK_DPI_SCALE \
    --name libreoffice \
    bghost/libreoffice:edge
