image: docker:latest
services:
    - docker:dind


before_script:
    - apk upgrade -U && apk add bash
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

chromium:edge:
    script:
        - cd chromium
        - export registry="registry.gitlab.com/bghost/dockerfiles/"
        - export ID=1000
        - export GID=1000
        - export PLUGDEV=240
        - bash ./build edge

chromium:sid:
    script:
        - cd chromium
        - export registry="registry.gitlab.com/bghost/dockerfiles/"
        - export ID=1000
        - export GID=1000
        - export PLUGDEV=240
        - bash ./build sid
