image: docker:latest
services:
    - docker:dind

before_script:
    - apk upgrade -U && apk add bash
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - export REGISTRY="registry.gitlab.com/bghost/dockerfiles/"
    - export PUSH="true"
    # Change below to match the user and group ID's
    # on the target host machine
    - export ID=1000
    - export GID=1000
    - export PLUGDEV=240
    - export AUDIO=18


wireshark:buster:
    script:
        - cd wireshark
        - bash ./build buster
          
signal-desktop:bionic:
        - cd signal-desktop
        - bash ./build bionic

riot:cosmic:
    script:
        - cd riot
        - bash ./build cosmic
