image: docker:latest
services:
    - docker:dind


before_script:
    - apk upgrade -U && apk add bash

chromium:edge:
    script:
        - cd chromium
        - export ID=1000
        - export GID=1000
        - export PLUGDEV=240
        - bash ./build edge

chromium:sid:
    script:
        - cd chromium
        - export ID=1000
        - export GID=1000
        - export PLUGDEV=240
        - bash ./build sid
