image: docker:latest

before_script:
    - apk upgrade -U && apk add bash

chromium:edge:
    script:
        - cd chromium
        - bash ./build edge

chromium:sid:
    script:
        - cd chromium
        - bash ./build sid
