#!/bin/bash

set -euo pipefail

if [ -z "$registry" ]; then
    registry=
fi

user='bghost'
repo='signal-desktop'
tag='bionic'

# set environment vars
if [ -z "$GID" ]; then
    export GID=$(id -g)
fi
if [ -z "$ID" ]; then
    export ID=$(id -u)
fi

# build the container:
docker build \
    --build-arg GID=${GID} \
    --build-arg ID=${ID} \
    -t ${registry}${user}/${repo}:${tag} .

docker push ${registry}${user}/${repo}:${tag}

# clean up our host environment
unset {GID,ID}
