#!/bin/bash

set -euo pipefail

user='bghost'
repo='signal-desktop'
tag='bionic'

# set environment vars
export GID=$(id -g)
export ID=$(id -u)

# build the container:
docker build \
    --build-arg GID=${GID} \
    --build-arg ID=${ID} \
    -t ${user}/${repo}:${tag} .

# clean up our host environment
unset {GID,ID}
