#!/bin/bash

set -euo pipefail

if [ -z "$registry" ]; then
    registry=
fi

user='bghost'
repo='chromium'
tag=${1:-edge}

# set environment vars
if [ -z "$GID" ]; then
    export GID=$(id -g)
fi
if [ -z "$PLUGDEV" ]; then
    export PLUGDEV=$(/bin/grep "plugdev" /etc/group | cut -d ':' -f 3)
fi
if [ -z "$ID" ]; then
    export ID=$(id -u)
fi

# build the container:
docker build \
    --build-arg GID=${GID} \
    --build-arg ID=${ID} \
    --build-arg PLUGDEV=${PLUGDEV} \
    -t ${registry}${user}/${repo}:${tag} $(find . -type d -name ${tag})

docker push ${registry}${user}/${repo}:${tag}

# clean up our host environment
unset {GID,PLUGDEV,ID}
