#!/bin/bash

# You will want the custom seccomp profile from Jessie Frazzelle
# https://raw.githubusercontent.com/jessfraz/dotfiles/master/etc/docker/seccomp/chrome.json

# Use bghost/wireshark:buster by default
tag="${1:-buster}"

docker run --rm -d \
    -c 4 \
    -m 1024M \
    -v /etc/localtime:/etc/localtime:ro \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e "DISPLAY=unix${DISPLAY}" \
    --name wireshark \
    bghost/wireshark:"${tag}"
